I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/splash.rpy", line 4, in script
    init -100 python:
  File "game/splash.rpy", line 9, in <module>
    renpy.error("DDLC archive files not found in /game folder. Check installation and try again.")
Exception: DDLC archive files not found in /game folder. Check installation and try again.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/splash.rpy", line 4, in script
    init -100 python:
  File "C:\Users\mwsch\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\mwsch\Desktop\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/splash.rpy", line 9, in <module>
    renpy.error("DDLC archive files not found in /game folder. Check installation and try again.")
  File "C:\Users\mwsch\Desktop\renpy-7.3.5-sdk\renpy\exports.py", line 2416, in error
    _error_handlers[-1](msg)
  File "C:\Users\mwsch\Desktop\renpy-7.3.5-sdk\renpy\exports.py", line 2393, in _error
    raise Exception(msg)
Exception: DDLC archive files not found in /game folder. Check installation and try again.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
 
Fri Jul 30 00:02:37 2021
